name: SkyBlock
version: 1.0
main: net.neferett.linaris.skyblock.Main
depend: [BukkitAPI, Holograms]
commands:
  kit:
  kits:
  money:
  level:
  spawn:
  classement:
  ec:
  enderchest:
  back:
  pay:
  craft:
  givekits: